### ISSUE TITLE
Rows not clearing when date has past

### ISSUE THREAD

**Issue by magfinn** [magfinn/Pencil-It-In#1]
I want the code to clear the text within <textarea class = "col-md-10 description"/> for "this" div. When I try to hide() or display: none the entire blocks are removed. I want to keep the div, but remove the text. 

`<script>
            if (blockTime < thisHour) {
                $(this).removeClass("future");
                $(this).removeClass("present");
                $(this).addClass("past");
<script>`

**Comment by lawless15** [comment]
Good Morning!

If I understand what you want to do, I think you either want to toggle the text or replace the text?

Remember I am not a JavaScript guru. I have taken classes and I use it occasionally. Also, there are a million ways to do one thing. It comes to preference, scalability, and/or functionality when you choose your path. That being said, maybe this will help.

Let's assume you want the current hour to show a blank instead of the save data.

For toggling the text you are keeping the data in the array the same, just changing visibility.  You can do this by changing the text color to transparent given a specific criteria:

For .js

else if (blockTime === thisHour) {
                $(this).removeClass("past");
                $(this).removeClass("future");
                $(this).addClass("hide");
                
            } 

for .css

.hide {
    background-color: #d3d3d3;
    opacity: 0.0;
}

For replacement, you would either replace or remove the data for that time. To keep continuity of the array, you would likely want to replace. If you delete, your array would be missing a row and depending on what all you are adding to your app, it could create issues. To replace, you are setting that row in the array to a blank string:

   if (thisHour === 8) {
        "";
    }
    else {$("#hour8 .description").val(localStorage.getItem("hour8"));
    }

For either, you could add a button or some other trigger under a function to this logic. 

I tested both and they worked. You can adjust the specific time you want to hide. Hope this sends you in the right direction.

**Comment by magfinn** [comment]
Thanks @lawless15! 

It definitely got me on the right track. I don't know if I was doing something wrong, but I couldn't get them to clear permanently through one of these methods. They would be hidden until I made the time between 8-5 again. 

Anyway, this ended up working. It's lengthy and ugly, but it works :) 

`$(document).ready(function () {
    timeTracker();
    if(thisHour>17) {
        $(".time-block").each (function(){
            var text = "";
            var time = $(this).attr("id");
            $(this).addClass("past");

            localStorage.setItem(time,text);
            $("#hour8 .description").val(localStorage.getItem("hour8"));
            $("#hour9 .description").val(localStorage.getItem("hour9"));
            $("#hour10 .description").val(localStorage.getItem("hour10"));
            $("#hour11 .description").val(localStorage.getItem("hour11"));
            $("#hour12 .description").val(localStorage.getItem("hour12"));
            $("#hour13 .description").val(localStorage.getItem("hour13"));
            $("#hour14 .description").val(localStorage.getItem("hour14"));
            $("#hour15 .description").val(localStorage.getItem("hour15"));
            $("#hour16 .description").val(localStorage.getItem("hour16"));
            $("#hour17 .description").val(localStorage.getItem("hour17"));
        });
    } else {
    saveEntries();
    }
});`

**Comment by magfinn** [comment]
@lawless15 I appreciate the help!
